import pyttsx3
from pyttsx3 import engine
engine = pyttsx3.init()
voices = engine.getProperty('voices')
for voice in voices:
    engine.setProperty('voice', voice.id)
    engine.say('The Road not Taken,        by Robert Frost')
    engine.say('Two roads diverged in a yellow wood,')
    engine.say('And sorry I could not travel both')
    engine.say('And be one traveler, long I stood')
    engine.say('And looked down one as far as I could')
    engine.say('To where it bent in the undergrowth;')
    engine.say('Then took the other, as just as fair,')
    engine.say('And having perhaps the better claim,')
    engine.say('Because it was grassy and wanted wear;')
    engine.say('Though as for that the passing there')
    engine.say('Had worn them really about the same,')
    engine.say('And both that morning equally lay')
    engine.say('In leaves no step had trodden black')
    engine.say('Oh, I kept the first for another day!')
    engine.say('Yet knowing how way leads on to way,')
    engine.say('I doubted if I should ever come back.')
    engine.say('I shall be telling this with a sigh')
    engine.say('Somewhere ages and ages hence:')
    engine.say('Two roads diverged in a wood, and I—')
    engine.say('I took the one less traveled by,')
    engine.say('And that has made all the difference.')
engine.runAndWait()
